fix(yololoss.py): for images without annotation boxes, they do not participate in loss calculation
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 5, 0] because the unspecified
dimension size -1 can be any value and is ambiguous